FROM python:3.6.1-alpine

RUN pip install awscli boto3
RUN apk update ** apk add git
ADD ./static/index.html /static/index.html
ADD ./dynamic/index.html /dynamic/index.html
ADD ./dynamic.py dynamic.py

#ENTRYPOINT ["/bin/ash"]
