apiVersion: v1
kind: List
items:
- apiVersion: operator.aws/v1alpha1
  kind: S3Bucket
  metadata:
    name: aws-operator-workshop-<APPEND_DATA_HERE>
  spec:
    versioning: false
    accessControl: PublicRead
    website:
      enabled: true
      indexPage: index.html
      errorPage: 500.html
    logging:
      enabled: false
      prefix: "archive"

- apiVersion: batch/v1
  kind: Job
  metadata:
    name: static-hydrate
  spec:
    template:
      spec:
        containers:
        - name: hydrate
          image: omarlari/operator-demo-hydrate
          imagePullPolicy: Always
          env:
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: aws-operator-workshop-<APPEND_DATA_HERE>
                  key: bucketName
          command: ["aws"]
          args: ["s3", "cp", "static/index.html", "s3://$(S3_BUCKET)"]
        restartPolicy: Never
    backoffLimit: 5
